import { makeStyles, shorthands, tokens } from '@fluentui/react-components';
import { shadows } from '../../styles/shadows';
import { spacing } from '../../styles/typography';
import { colors } from '../../styles/colors';

const useStyles = makeStyles({
  sidebar: {
    width: '260px',
    minWidth: '260px',
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.padding(spacing.lg),
    backgroundColor: tokens.colorNeutralBackground2,
    ...shorthands.borderRight('1px', 'solid', tokens.colorNeutralStroke1),
    ...shorthands.overflow('hidden'),
    boxSizing: 'border-box',
    boxShadow: shadows.subtle.sm,
    position: 'relative',
    zIndex: 10,
    animation: 'fadeInLeft 0.4s ease-out',
  },
  sidebarContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
    flex: 1,
    minHeight: 0,
  },
  sidebarNav: {
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap(spacing.xs),
  },
  sidebarNavItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    ...shorthands.padding(spacing.sm, spacing.md),
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    color: tokens.colorNeutralForeground1,
    cursor: 'pointer',
    fontSize: tokens.fontSizeBase400,
    fontWeight: tokens.fontWeightMedium,
    lineHeight: '1.4',
    letterSpacing: '0.025em',
    transitionProperty: 'transform, background-color, color, box-shadow',
    transitionDuration: tokens.durationFaster,
    transitionTimingFunction: tokens.curveDecelerateMid,
    boxShadow: shadows.components.card,
    animation: 'fadeInUp 0.3s ease-out',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
      transform: 'translateX(2px) scale(1.02)',
      boxShadow: shadows.interactive.hover,
    },
    ':active': {
      transform: 'translateX(1px) scale(0.98)',
      animation: 'buttonPress 0.15s ease-out',
    },
    ':focus-visible': {
      outlineStyle: 'solid',
      outlineWidth: '2px',
      outlineColor: tokens.colorBrandStroke1,
      outlineOffset: '2px',
      boxShadow: shadows.interactive.focus,
      animation: 'focusRing 0.3s ease-out',
    },
  },
  sidebarNavItemActive: {
    backgroundColor: `${tokens.colorBrandBackgroundSelected} !important`,
    color: '#FFFFFF !important',
    fontWeight: tokens.fontWeightSemibold,
    fontSize: tokens.fontSizeBase400,
    lineHeight: '1.4',
    letterSpacing: '0.025em',
    boxShadow: `inset 2px 0 0 ${tokens.colorBrandStroke1}, ${shadows.brand.sm} !important`,
    ':hover': {
      backgroundColor: `${tokens.colorBrandBackgroundHover} !important`,
      color: '#FFFFFF !important',
      transform: 'translateX(2px) scale(1.02)',
      boxShadow: `inset 2px 0 0 ${tokens.colorBrandStroke1}, ${shadows.interactive.hover} !important`,
    },
    ':active': {
      backgroundColor: `${tokens.colorBrandBackgroundPressed} !important`,
      color: '#FFFFFF !important',
      transform: 'translateX(1px) scale(0.98)',
      animation: 'buttonPress 0.15s ease-out',
    },
    ':focus-visible': {
      backgroundColor: `${tokens.colorBrandBackgroundSelected} !important`,
      color: '#FFFFFF !important',
      outlineStyle: 'solid',
      outlineWidth: '2px',
      outlineColor: tokens.colorBrandStroke1,
      outlineOffset: '2px',
      boxShadow: `inset 2px 0 0 ${tokens.colorBrandStroke1}, ${shadows.interactive.focus} !important`,
      animation: 'focusRing 0.3s ease-out',
    },
  },
  sidebarSectionHeader: {
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorNeutralForeground4,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    lineHeight: '1.2',
    ...shorthands.padding('0', spacing.md),
    marginTop: spacing['2xl'],
    marginBottom: spacing.sm,
  },
  sidebarScrollArea: {
    flexGrow: 1,
    ...shorthands.overflow('auto'),
    minHeight: 0,
    scrollBehavior: 'smooth',
  },
  sidebarLink: {
    fontSize: tokens.fontSizeBase300,
    color: tokens.colorNeutralForeground2,
    textDecorationLine: 'none',
    display: 'block',
    ...shorthands.padding(spacing.xs, spacing.md),
    ...shorthands.borderRadius(tokens.borderRadiusSmall),
    ...shorthands.overflow('hidden'),
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontWeight: tokens.fontWeightNormal,
    lineHeight: '1.4',
    letterSpacing: '0.025em',
    transitionProperty: 'transform, background-color, color, box-shadow',
    transitionDuration: tokens.durationFaster,
    transitionTimingFunction: tokens.curveDecelerateMid,
    boxShadow: shadows.subtle.xs,
    animation: 'fadeInUp 0.3s ease-out',
    ':hover': {
      color: tokens.colorNeutralForeground1,
      backgroundColor: tokens.colorNeutralBackground1Hover,
      transform: 'translateX(2px) scale(1.01)',
      boxShadow: shadows.subtle.sm,
    },
    ':active': {
      transform: 'translateX(1px) scale(0.99)',
      animation: 'buttonPress 0.15s ease-out',
    },
    ':focus-visible': {
      outlineStyle: 'solid',
      outlineWidth: '2px',
      outlineColor: tokens.colorBrandStroke1,
      outlineOffset: '2px',
      boxShadow: shadows.interactive.focus,
      animation: 'focusRing 0.3s ease-out',
    },
  },
});

export default useStyles;


